FORMAT: 1A
HOST: http://api.zebra.com

# supplies
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Supplies API**

## Supplies Collection [/supplies]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, 
          "name": "one name",
          "description": "one description"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Supply [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Supply [/notes/{id}]
A single Supply object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Supply [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
