FORMAT: 1A
HOST: http://api.zebra.com

# Zebra Supplies API
Supplies API is a service used to find supplies for Zebra printers.

# Group Supplies
Supply related resources of the **Supplies API**

## Supply [/supplies/{supplyId}]

+ Model (application/json)

    + Body

            {
              "class": [ "message" ],
              "properties": { 
                    "message": "Hello World!" 
              },
              "links": [
                    { "rel": "self" , "href": "/message" }
              ]
            }
            
+ Headers
    
        Accept-Language: en-US

### Retrieve a Supply [GET]
+ Response 200

    [Supply][]

## Supplies Collection [/supplies{?page,?pageSize,?sortBy,?sort,?type,?printer,?mediaType,?width,?length,?distanceUnit,?printTech,?chemResist,?env,?maxTemp,?minTemp,?tempUnit,?adhesive,?surface,?surfaceShape,?surfaceCond,?acceptance}]

+ Model (application/json)

    + Body

            {
              "data": [
                    { }
              ]
            }
            
+ Parameters
    - page = `1` (optional, number, `1`) 
    - pageSize = `10` (optional, number, `10`)
    - sortBy (optional, string, `width, length, perforation`)
    - sort (optional, string)
        + Values
            + `asc`
            + `desc`
    - type (required, string, `media, ribbon`)
    - printer (required, string, `105SL`) 
    - mediaType (required, string, `paper, synthetic`)
    - width (optional, number, `11.10`)
    - length (optional, number, `12.30`)
    - distanceUnit (optional, string)
        + Values
            + `metric`
            + `imperial`
    - printTech (optional, string, `DT, TT`)
    - chemResist (required, string, `none, weak, medium, strong`)
    - env (required, string, `indoor, outdoor`)
    - maxTemp (required, number, `-10`)
    - minTemp (required, number, `40`)
    - tempUnit (required, string)
        + Values
            + `C`
            + `F`
    - adhesive (optional, string, `permanent, removable`)
    - surface (optional, string, `paper, plastic`)
    - surfaceShape (optional, string, `smooth, rough`)
    - surfaceCond (optional, string, `smooth, rough`)
    - acceptance (optional, string)
        + Values
            + `none`
            + `CSA`
            + `UL`
            
+ Headers
    
        Accept-Language: en-US

### List all Supplies [GET]
+ Response 200

    [Supplies Collection][]
