FORMAT: 1A
HOST: http://api.zebra.com

# supplies
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Supplies API**

## Supplies Collection [/supplies{?page,pageSize,sortBy,sort,type,printer,mediaType,width,length,distanceUnit,printTech,chemResist,env,maxTemp,minTemp,tempUnit,adhesive,surface,surfaceShape,surfaceCond,acceptance}]
### List all Notes [GET]
+ Parameters
    - page (optional, number, `1`) ... Numeric `page` number of the search result list.
    - pageSize (optional, number, `10`) ... Numeric `pageSize`

+ Response 200 (application/json)

        [{
          "id": 1, 
          "name": "one name",
          "description": "one description"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
